name: getx_ecosystem_trial
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  avatar_glow: ^2.0.1
  cupertino_icons: ^1.0.0
  dio: ^4.0.0
  flutter:
    sdk: flutter
  flutter_svg: ^0.22.0
  freezed_annotation: ^0.14.2
  get: ^4.1.4
  get_storage: ^2.0.2
  google_maps_flutter: ^2.0.6
  google_maps_flutter_web: ^0.3.0
  location: ^4.1.1
  speech_to_text: ^4.1.1-nullsafety

dev_dependencies:
  build_runner: ^2.0.4
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2
  json_serializable: ^4.1.3
  lint: ^1.5.3

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/map_style.txt

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
