name: getx_ecosystem_trial
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  dio: ^3.0.10
  flutter_svg: ^0.19.1
  get: 3.12.1
  get_storage: ^1.3.1
  google_maps_flutter: ^1.0.6
  google_maps_flutter_web: ^0.1.0+7
  location: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1
  lint: ^1.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/map_style.txt

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
