version: '3'

services:
    api:
        build: covid-api/.
        container_name: covid-api
        network_mode: "host"

    live-update:
        build: live-update/.
        container_name: live-update
        network_mode: "host"
    
    hotspot-evaluate:
        build: hotspot-evaluate/.
        container_name: hotspot-evaluate
        network_mode: "host"
