version: '3'

services:
    postgresql:
        image: postgres
        container_name: jarvisdb
        ports:
             - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: qwertyuiop
            POSTGRES_DB: jarvis
    api:
        build: api/.
        container_name: api
        network_mode: "host"

    live-update:
        build: live-update/.
        container_name: live-update
        network_mode: "host"