version: '3'

services:
    postgresql:
        image: postgres
        container_name: post-pandemic-db
        ports:
             - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 7878
            POSTGRES_DB: post-pandemic-db
    api:
        build: api/.
        container_name: api
        network_mode: "host"

    live-update:
        build: live-update/.
        container_name: live-update
        network_mode: "host"