version: '3'

services:
    zookeeper:
        image: wurstmeister/zookeeper
        container_name: zookeeper
        ports: 
            - "2181:2181"

    kafka:
        image: wurstmeister/kafka
        container_name: kafka
        ports: 
            - "9092:9092"
        environment: 
            KAFKA_ADVERTISED_HOST_NAME: localhost
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            
    postgresql:
        image: postgres
        container_name: post-pandemic-db
        ports:
             - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            PGDATA: /var/postgres_data
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 7878
            POSTGRES_DB: post-pandemic-db
volumes:
    postgres_data:
        external: true